create database embaixada;
use embaixada;

create table passaporte(
idpassaporte int unsigned not null auto_increment,
tipo char(1) not null,
numeroPassaporte varchar (8),
nome varchar(100) not null,
nacionalidade varchar (15) not null,
dataNascimento datetime("yyyy:dd:mm") not null,
sexo char(1) not null,
naturalidade varchar(15) not null,
filiacao1 varchar(50) not null,
filiacao2 varchar(50),
dataExpedicao datetime("yyyy:dd:mm") not null,
validade datetime("yyyy:dd:mm") not null,
orgaoExpeditor char(9) not null,
primary key(idpassaporte),
);
create table cidadao(
idcidadao int unsigned not null auto_increment,
tipo char(1),
paisEmissor char(3),
numeroPassaporte varchar (8),
nome varchar(100),
nancionalidade varchar (15),
dataNascimento datetime("yyyy:dd:mm"),
sexo char(1),
naturalidade varchar(15),
filiacao1 varchar(50),
filiacao2 varchar(50),
dataExpedicao datetime("yyyy:dd:mm"),
validade datetime("yyyy:dd:mm"),
orgaoExpeditor char(9),
primary key(idcidadao),
);

create table casamento(
idcasamento int unsigned not null auto_increment,
declarante varchar (30),
dia datetime("yyyy:dd:mm"),
localidade varchar (20),
numeroRgistroCivil varchar (20),
conjuge varchar(30),
nacionalidade char (3),
dataNascimento datetime("yyyy:dd:mm"),
localNascimento varchar (10),
profissao varchar (10),
estadoCivilAnterior varchar(10),
nomeCasamentoAnterior varchar(10),
nomePai varchar(30),
nacionalidadeP varchar(10),
dataNascimentoP datetime("yyyy:dd:mm"),
dataObto datetime("yyyy:dd:mm"),
nomeMae varchar(30),
nacionalidadeM varchar(10),
domicilioPais varchar(40),
primary key(idcasamento),
);
create table autorizacao(
idautorizacao int unsigned not null auto_increment,
nomeMenor varchar (30) not null,
numeroPassaporte varchar (8),
orgaoEx char (5),
dataEx datetime("yyyy:dd:mm"),
residencia varchar(30),
pais char(3),
nomePai varchar (30),
nomeMae varchar(30),
nomeAutorizar varchar(30),
primary key (idautorizacao),
);
create table cpf(
idcpf int unsigned not null auto_increment,
motivo varchar(10),
nome varchar(30),
sexo char(1),
dataNascimento datetime("yyyy:dd:mm"),
nacionalidade char (3),
nomeMae varchar(30),
endereco varchar(20),
telefone int(15),
dataSaidaPais datetime("yyyy:dd:mm"),
titulo int (10),
email varchar (20),
cpf int (11),
primary key(idcpf),
);
create table nascimento(
idnascimento int unsigned not null auto_increment,
nome varchar(30),
dataNascimento datetime("yyyy:dd:mm"),
paisNascimento char(3),
endereco varchar(30),
nomePai varchar (30),
nomeMae varchar (30),
primary key(idnascimento),
);
create table divorcio(
nomeRequerente varchar(30) not null,
nomeConjuge varchar(30) not null,
pais char(3) not null,
dataSolitacao datetime("yyyy:dd:mm") not null,
endereco varchar (20)not null,
contato int(11)not null,
primary key(iddivorcio),
);
create table obito(
idobto int unsigned not null auto_increment,
nome varchar(30) not null,
dataNascimento datetime("yyyy:dd:mm") not null,
dataObito datetime("yyyy:dd:mm") not null,
endereco varchar(30) not null,
paisFalecido char(3) not null,
numeroPassaporte varchar(8) not null,
primary key(idobito) not null,
);
create table nacionalidade(
idnacionalidade int unsigned not null auto_increment,
dataSolicitacao datetime("yyyy:dd:mm") not null,
primary key(idnacionalidade),
);
create table taxas(
idtaxas int unsigned not null auto_increment,
taxaPassaporte float(80),
taxaCasamento float(80),
taxaAutorizacaoe float(80),
taxaCpf float(80),
taxaNascimento float(80),
taxaDivorcio float(80),
taxaObito float(80),
taxaNacionalidade float(80),
primary key(idtaxas),
);